name: tests and coverage with matlab

on:
  push:
    branches:
      - dev
      - main
    paths:
      - '**.m'
      - '.github/workflows/*.m'
  pull_request:
    branches: ['*']
    paths:
      - '**.m'
      - '.github/workflows/*.m'
  schedule:
    - cron: "1 1 1 * *"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  tests_matlab:
    runs-on: ubuntu-20.04

    steps:
      - name: Install MATLAB
        uses: matlab-actions/setup-matlab@v1.2.0
        with:
          # MATLAB release to set up R2020a
          release: R2020a

      - name: Install CPP_ROI
        uses: actions/checkout@v3
        with:
          submodules: true
          fetch-depth: 1

      - name: Install SPM
        run: |
          git clone https://github.com/spm/spm12.git --depth 1

      - name: Install Moxunit and MOcov
        run: |
          git clone https://github.com/MOxUnit/MOxUnit.git --depth 1
          git clone https://github.com/MOcov/MOcov.git --depth 1

      - name: Add bids-matlab
        run: make install_dev

      - name: Run commands
        uses: matlab-actions/run-command@v1.1.0
        with:
          command: cd(fullfile(getenv('GITHUB_WORKSPACE'), '.github', 'workflows')); run tests_matlab;

      - name: Run tests
        run: |
          cat test_report.log | grep 0
          bash <(curl -s https://codecov.io/bash)

      - name: Code coverage
        uses: codecov/codecov-action@v3
        with:
          file: coverage.xml # optional
          flags: unittests # optional
          name: codecov-umbrella # optional
          fail_ci_if_error: true # optional (default = false)
