name: allcontributors-auto-detect

on:
  schedule:
    # Run nightly 1am
    - cron: 0 1 1 * *

  # You can also have it check for changes on each push to master
  push:
    branches:
      - main

jobs:
  Update:
    name: Generate
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Tributors Update

        # Important! Update to release https://github.com/con/tributors
        uses: con/tributors@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:

          # Single text list (space separated) of parsers, leave unset to auto-detect
          parsers: unset

          # INFO, DEBUG, ERROR, WARNING, etc.
          log_level: DEBUG

          # If files already exist and an init is done, force overwrite
          force: true

          # the minimum number of contributions required to add a user
          threshold: 1

      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v4
        with:
          commit-message: update tributors
          base: main
          delete-branch: true
          title: '[BOT] update tributors'
          body: 'done via this [GitHub Action](https://github.com/cpp-lln-lab/CPP_ROI/blob/main/.github/workflows/update-contributors.yml)'

      - name: Check outputs
        run: |
          echo "Pull Request Number - ${{ steps.cpr.outputs.pull-request-number }}"
          echo "Pull Request URL - ${{ steps.cpr.outputs.pull-request-url }}"
